build_task:
  freebsd_instance:
    matrix:
      image_family: freebsd-13-0-snap
      image_family: freebsd-12-1
    cpu: 2
    memory: 4G

  timeout_in: 60m

  install_script:
    - chmod +x ports/ci/cirrus/install_deps.sh
    - ./ports/ci/cirrus/install_deps.sh

  script:
    - chmod +x ports/ci/cirrus/build.sh
    - ./ports/ci/cirrus/build.sh

  deploy_script:
    - chmod +x ports/ci/cirrus/deploy.sh
    - ./ports/ci/cirrus/deploy.sh
