build_task:
  freebsd_instance:
    matrix:
      image: freebsd-12-0-release-amd64
      image: freebsd-11-2-release-amd64
      #image: freebsd-11-1-release-amd64
      #image: freebsd-10-4-release-amd64
    cpu: 2
    memory: 4G

  timeout_in: 60m

  install_script:
    - chmod +x ports/ci/cirrus/install_deps.sh
    - ./ports/ci/cirrus/install_deps.sh

  script:
    - chmod +x ports/ci/cirrus/build.sh
    - ./ports/ci/cirrus/build.sh

deploy_task:
  depends_on:
    - build
  allow_failures: true

  script:
    - chmod +x ports/ci/cirrus/deploy.sh
    - ./ports/ci/cirrus/deploy.sh
