post_install() {
    cat << EOF

Webcamoid requires at least one of the packages from each of the
following groups to be installed for fully functioning.

Capture backend:

    - v4l-utils (RECOMMENDED)

Codec frameworks:

    - ffmpeg (RECOMMENDED)
    - gst-plugins-*

Audio playback:

    - libpulse (RECOMMENDED)
    - alsa-lib
    - jack
    - qt5-multimedia

Virtual camera management:

    - kde-cli-tools (RECOMMENDED)
    - gksu

    EOF
}
