Document: webcamoid
Title: Debian webcamoid Manual
Author: <insert document author here>
Abstract: This manual describes what webcamoid is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/webcamoid/webcamoid.sgml.gz

Format: postscript
Files: /usr/share/doc/webcamoid/webcamoid.ps.gz

Format: text
Files: /usr/share/doc/webcamoid/webcamoid.text.gz

Format: HTML
Index: /usr/share/doc/webcamoid/html/index.html
Files: /usr/share/doc/webcamoid/html/*.html
