name: Debian

on: [push, pull_request]

env:
  QTIFWVER: 4.8.1
  APPIMAGEVER: continuous

jobs:
  build:
    name: Debian x86_64
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
       include:
         - dockerimg: debian:latest
           compiler: gcc
         - dockerimg: debian:latest
           compiler: clang
         - dockerimg: debian:testing
           compiler: gcc
         - dockerimg: debian:testing
           compiler: clang
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: true
        token: ${{ secrets.UPLOAD_TOKEN }}
    - name: Release build
      uses: addnab/docker-run-action@v3
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: gcr.io
        image: ${{ matrix.dockerimg }}
        options: >-
          -v ${{ github.workspace }}:/sources
          -e GITHUB_REF=${{ github.ref }}
          -e GITHUB_SERVER_URL=${{ github.server_url }}
          -e GITHUB_REPOSITORY=${{ github.repository }}
          -e GITHUB_RUN_ID=${{ github.run_id }}
          -e GIT_COMMIT_HASH=${{ github.sha }}
          -e GIT_BRANCH_NAME=${{ github.ref_name }}
          -e APPIMAGEVER=${{ env.APPIMAGEVER }}
          -e COMPILER=${{ matrix.compiler }}
          -e DOCKERIMG=${{ matrix.dockerimg }}
          -e QTIFWVER=${{ env.QTIFWVER }}
        run: |
          cd /sources
          echo
          echo Install dependencies
          echo
          chmod +x ports/ci/linux-debian/install_deps.sh
          ./ports/ci/linux-debian/install_deps.sh
          echo
          echo Release Build
          echo
          chmod +x ports/ci/linux-debian/build.sh
          ./ports/ci/linux-debian/build.sh
          echo
          echo Release Deploy
          echo
          chmod +x ports/ci/linux-debian/deploy.sh
          ./ports/ci/linux-debian/deploy.sh
    - name: Daily build
      uses: addnab/docker-run-action@v3
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: gcr.io
        image: ${{ matrix.dockerimg }}
        options: >-
          -v ${{ github.workspace }}:/sources
          -e GITHUB_REF=${{ github.ref }}
          -e GITHUB_SERVER_URL=${{ github.server_url }}
          -e GITHUB_REPOSITORY=${{ github.repository }}
          -e GITHUB_RUN_ID=${{ github.run_id }}
          -e GIT_COMMIT_HASH=${{ github.sha }}
          -e GIT_BRANCH_NAME=${{ github.ref_name }}
          -e APPIMAGEVER=${{ env.APPIMAGEVER }}
          -e COMPILER=${{ matrix.compiler }}
          -e DOCKERIMG=${{ matrix.dockerimg }}
          -e QTIFWVER=${{ env.QTIFWVER }}
          -e DAILY_BUILD=1
        run: |
          cd /sources
          echo
          echo Install dependencies
          echo
          chmod +x ports/ci/linux-debian/install_deps.sh
          ./ports/ci/linux-debian/install_deps.sh
          echo
          echo Daily Build
          echo
          chmod +x ports/ci/linux-debian/build.sh
          ./ports/ci/linux-debian/build.sh
          echo
          echo Daily Deploy
          echo
          chmod +x ports/ci/linux-debian/deploy.sh
          ./ports/ci/linux-debian/deploy.sh
